### PR TITLE
PyInstaller (Windows EXE) Support

### PR DESCRIPTION
**Pull request by aboredpervert**
Now that Python 3.10 fixed their bug I can bring this.

As discussed in #69, this is all the work needed so it's possible to build the scraper as a standalone EXE for Windows, that does not require messing with Python or pip to get running. Just download and run.

I have also added some documentation on how to build it and programming considerations.

### CODE REVIEW

**Comment by DIGITALCRIMINALS** [comment]
Thank for you this :pray: 

So I can start building the script and upload it to github when releasing a new version?

**Comment by aboredpervert** [comment]
> So I can start building the script and upload it to github when releasing a new version?

That is the goal, yes, to make it much easier for non-technical people to run it.

I see there are conflicts, I will have to fix them.

**Comment by aboredpervert** [comment]
Conflicts are fixed, it's good to go.

**Comment by DIGITALCRIMINALS** [comment]
I've got massive commits coming up that will change everything, but I'll fix it

**Pull request merged**
