### PR TITLE
Syntax Checker

### PR DESCRIPTION
**Pull request by americanseeder1865**
I think I am doing this right? May need to change URL to your repo instead of mine. 

This should check to make sure we don't have any python syntax errors going on every time we commit. Should give us a gold star if we pass lmao

### CODE REVIEW

**Comment by DIGITALCRIMINALS** [comment]
I can't access any of these commits lol

**Comment by LunarPenguin** [comment]
This PR seems to based of a previous version of his repo (`OnlyFans-old`) there now seems to be a new repo `OnlyFans` with exactly the same commits. so maybe @americanseeder1865 can change the base of the PR to that new repo.

**Comment by americanseeder1865** [comment]
At one point, this repo disappeared and I made my repo my own. I will fork it again and redo some stuff

**Comment by americanseeder1865** [comment]
Going to close and resubmit once I am done.

**Comment by americanseeder1865** [comment]
Closing and will resubmit when done

**Pull request closed without merging**
