### PR TITLE
Fix for Stories API change on Onlyfans

### PR DESCRIPTION
**Pull request by eclipseo**
Fix for #604 

> File /home/bob/Downloads/OnlyFans/apis/onlyfans/classes/user_model.py, line 283, in get_highlights
>    results = [create_highlight(x) for x in results[data]]
> KeyError: 'data'

The 'data' key was replaced with 'list'.

### CODE REVIEW

**Comment by darkplace77** [comment]
Hi, this make the script not crash. but not downloading the stories...

**Comment by alexey-romero** [comment]
you're the man

**Comment by MahewIsTaken** [comment]
> Hi, this make the script not crash. but not downloading the stories...

Same thing for me, only scraping header and avatar but nothing else.

**Review by AstraLuma — APPROVED** [review]
Yup, the data seems to be moved to `list`. :+1: 

The inner schema appears to be as expected. (that is, unchanged)

As for the reports of failed scraping, :woman_shrugging: I don't think it's dropping data?

**Comment by edoardottt** [comment]
For the less expert ones, at least until the PR is accepted:
In the file `apis/onlyfans/classes/user_model.py` at line 284 change the line:
```
results = [create_highlight(x) for x in results["data"]]
```
to
```
results = [create_highlight(x) for x in results["list"]]
```
**Remember** to keep the indentation as you find it.

I don't know why to other people it seems it's not working, I just downloaded everything succesfully

**Comment by MahewIsTaken** [comment]
FYI if its not scraping posts, I downloaded 7.6.1 instead and just applied the fixes that are mentioned in other issues and it works for me now. Still have no idea why onlyfans-master doesnt work

**Comment by eclipseo** [comment]
Hello, I fixed the code to scrap the posts now, check the diff to see the changes in the API.

**Comment by MahewIsTaken** [comment]
> @darkplace77 @MahewIsTaken @Kubiksc @AstraLuma
> 
> Hello, I fixed the code to scrap the posts now, check the diff to see the changes in the API.

Traceback (most recent call last):
  File "C:\Users\myuser\Downloads\OnlyFans-master\start_ofd.py", line 9, in <module>
    from helpers.main_helper import OptionsFormat
  File "C:\Users\myuser\Downloads\OnlyFans-master\helpers\main_helper.py", line 44, in <module>
    from modules.onlyfans import OnlyFansDataScraper
  File "C:\Users\myuser\Downloads\OnlyFans-master\modules\onlyfans.py", line 137
    if "files" in media:
IndentationError: unexpected indent

I get this when trying to run the script after putting in the changes

**Comment by eclipseo** [comment]
can you post that files somewhere: C:\Users\myuser\Downloads\OnlyFans-master\modules\onlyfans.py on a Pastebin?
I can't repro, it works for me and I don't see any indentation problems in the file. Try redownloading OnlyFans-master.zip?

**Comment by MahewIsTaken** [comment]
> can you post that files somewhere: C:\Users\myuser\Downloads\OnlyFans-master\modules\onlyfans.py on a Pastebin? I can't repro, it works for me and I don't see any indentation problems in the file.
> 
> Try redownloading:
> 
> https://github.com/eclipseo/OnlyFans/archive/refs/heads/fix_api.zip

Script works after downloading however its not downloading any content still. This is what it looks like:
https://imgur.com/a/PGbw3vi

**Comment by eclipseo** [comment]
Does that model have stories?

**Comment by MahewIsTaken** [comment]
> 

Scraped one with stories and it worked aswell

**Comment by Dudeman456** [comment]
I am getting the following error:

Traceback (most recent call last):
  File "R:\OnlyFans\start_ofd.py", line 9, in <module>
    from helpers.main_helper import OptionsFormat
  File "R:\OnlyFans\helpers\main_helper.py", line 23, in <module>
    import orjson
ModuleNotFoundError: No module named 'orjson'

with both the fix_api and the latest gitbuild.

**Comment by dballs6666** [comment]
@eclipseo Hi bro, thanks for the solution but i'm using the version 7.2

How can I fix the download of stories for the version 7.2?. Can you help me please?

**Pull request merged**
